### PR TITLE
fix travis for mysql-devel

### PR DESCRIPTION
**Pull request by MaximilianMeister**
Signed-off-by: Maximilian Meister <mmeister@suse.de>

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
https://travis-ci.org/kubic-project/velum/jobs/271971574 from https://github.com/kubic-project/velum/pull/296

**Comment by vitoravelino** [comment]
What we did on Portus to fix this was upgrade the mariadb addon version to the latest. /cc @mssola

**Comment by MaximilianMeister** [comment]
> What we did on Portus to fix this was upgrade the mariadb addon version to the latest. /cc @mssola

@vitoravelino thanks for the hint, how is that done? i looked at https://github.com/SUSE/Portus/blob/master/.travis.yml#L75 and at least there it's the same version

**Comment by vitoravelino** [comment]
@MaximilianMeister we didn't merge it yet https://github.com/SUSE/Portus/pull/1401

**Comment by MaximilianMeister** [comment]
> @MaximilianMeister we didn't merge it yet SUSE/Portus#1401

@vitoravelino i see, the problem is our mariadb image in the product is `10.0` so we have to stick to that version. i wonder if there is another way to fix travis

**Comment by MaximilianMeister** [comment]
it works half way... now 2 jobs are green, others are red https://travis-ci.org/kubic-project/velum/builds/271979755?utm_source=github_status&utm_medium=notification

**Comment by vitoravelino** [comment]
No idea... =/

**Comment by MaximilianMeister** [comment]
re-triggered travis, and all jobs were green now... https://travis-ci.org/kubic-project/velum/builds/271979755

now let's do it 2 times more ...

**Comment by MaximilianMeister** [comment]
> now let's do it 2 times more ...

it was green 3 times now, i think it's good to be merged

**Comment by vitoravelino** [comment]
Nice work, @MaximilianMeister!

@mssola We should try to do the same in Portus.

**Comment by MaximilianMeister** [comment]
backport? @kiall @flavio

**Pull request merged**
