### PR TITLE
WIP: disable signup feature

### PR DESCRIPTION
**Pull request by flavio**
This PR allows a velum administrator to completely disable the signup feature. This is a requirement of the public cloud team, they want to perform the user creation only through a local command (this is coming after with another PR).

The PR also introduces the configuration mechanism used by Portus:
  * we provide sane settings inside of a `config/config.yml` file
  * users can override/extend them by doing any combination of:
     * provide a custom `config/config-local.yml` file
     * use environment variables

For example, to disable entirely the signup page the admin can start the velum container setting `VELUM_SIGNUP_ENABLED` to `"false"`.

This PR is a WIP, tests have not been extended yet.

### CODE REVIEW

**Comment by robdaemon** [comment]
This will slot in nicely with the RBAC work too 👍

**Comment by flavio** [comment]
I've seen you moved the config code to a dedicated gem: https://github.com/mssola/cconfig

I think this PR should be changed to use that gem :) I'll try to do that before leaving for vacations

**Comment by mssola** [comment]
This is now available on rubygems: https://rubygems.org/gems/cconfig

**Comment by flavio** [comment]
@bear454: does it still make sense to revamp this PR or should I just close it?

**Comment by bear454** [comment]
For Public Cloud, we'll be creating the admin user account via a `rake` task, and therefore have no need for the UI to create the admin user.

**Comment by ereslibre** [comment]
I think we can drop this one for now, right @flavio?

**Pull request closed without merging**
