### PR TITLE
Prevent exception in console during initial bootstrap

### PR DESCRIPTION
**Pull request by kiall**
As the data structure changes between bootstrap and monitoring, we
have to account for both in the code. This change will prevent the
exception without affecting behaviour.

### CODE REVIEW

**Comment by PI-Victor** [comment]
seems that there's already a PR to address this https://github.com/kubic-project/velum/pull/82/files

**Comment by kiall** [comment]
@PI-Victor that PR won't fix this issue, as it still includes:

    var unassigned = data.unassigned_minions;

which will cause the exception, as `data` does not have an `unassigned_minions` property.

**Comment by kiall** [comment]
Oh, maybe it will.. (It's been a few years since I touched JS!). Let me look again.

**Comment by PI-Victor** [comment]
i think it does through https://github.com/kubic-project/velum/pull/82/files#diff-398e9dc91ab41e7d183e081c72f8f161R33

**Comment by PI-Victor** [comment]
i don't oppose this change in any way, though :) lgtm.

**Pull request merged**
