### PR TITLE
ui: polishing and minor enhancements

### PR DESCRIPTION
**Pull request by vitoravelino**
Most of changes were done based on [wireframes](https://projects.invisionapp.com/share/PJBM8UUB2#/screens/236598224):

- General
  - Added missing Roboto Medium (used on panel titles for example)
  - Slightly larger line-height on `.panel-heading` to fit `.btn-sm`
  - Buttons on `.panel-heading` moved from `.btn-xs` to `.btn-sm`
- Configuration
  - Added missing `.panel-title` (except for proxy settings to avoid conflict)
- Overview page
  - Centered status icon to column name
  - Status text in the same column as icon
  - Aligned table data text in the middle
  - Wrong use of th instead of td on nodes table
  - Master checkbox aligned before role text
  - Changed update all nodes from button to link
- Overview and Discovery
  - Added text when Pending Nodes panel is empty

## Overview (before)

screenshot from 2017-06-28 13-04-03

## Overview (after)

screenshot from 2017-06-28 13-00-01

## Discovery page (before)

screenshot from 2017-06-28 13-05-19

## Discovery page (after)

screenshot from 2017-06-28 12-31-26

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
if the differences are really visible, could you add some screenshots once you're done with the coding?

**Comment by vitoravelino** [comment]
> if the differences are really visible, could you add some screenshots once you're done with the coding?

Sure. Didn't do yet because there still one change left. Will do as soon as I'm done with it. Don't worry!

**Comment by PI-Victor** [comment]
i think the current attached screenshot is pretty wicked tho. good job.

**Comment by vitoravelino** [comment]
> i think the current attached screenshot is pretty wicked tho. good job.

The wireframes are from Cierra not from myself. Hehe.

**Comment by vitoravelino** [comment]
Good to be reviewed!

**Comment by flavio** [comment]
I fixed the conflicts against master using the web UI. If everything passes I would merge the code

**Comment by flavio** [comment]
I merged it manually into master.

**Pull request closed without merging**
