### PR TITLE
Improve the style of "db is initializing" page [bsc#1047305]

### PR DESCRIPTION
**Pull request by flavio**
Try to use the same style as the main velum web application. This is something I hacked together in a couple of minutes. I think @vitoravelino will have lots of comments about that :)

## Before

before

## After

after

### CODE REVIEW

**Comment by vitoravelino** [comment]
After some quick tweaks I could come up with a lighter and darker options. Please vote with a reaction on which one you would prefer. Suggestions are welcome since my design skills are not so good.

**Comment by vitoravelino** [comment]
screenshot 2017-07-05 16 44 40

**Comment by vitoravelino** [comment]
screenshot 2017-07-05 16 50 09

**Comment by mssola** [comment]
They all look good, but if I had to chose one, I'd pick the latest image from @vitoravelino 👍

**Comment by ereslibre** [comment]
Another vote for @vitoravelino's dark version.

**Comment by flavio** [comment]
@vitoravelino : let's go with your dark style. Can you commit the changes straight into this branch?

**Comment by MaximilianMeister** [comment]
follow to keep the other static pages in sync https://github.com/kubic-project/velum/pull/245

**Pull request merged**
