### PR TITLE
[3.0] Add a feature spec for building cluster in Azure

### PR DESCRIPTION
**Pull request by bear454**
Backport of #584 .

### CODE REVIEW

**Comment by bear454** [comment]
[Add a feature spec for building cluster in Azure](https://trello.com/c/ah3QAPqa/1019-add-a-feature-spec-for-building-cluster-in-azure)

**Comment by jordimassaguerpla** [comment]
@bear454 : We need a bsc number to port fixes to this branch. I would say, if this goes along with a bug fix, then I am fine to merge this after we have release 3.0, so this is shipped as a maintenance updates. Right now we are only merging P1 fixes, but we will open the gates again in short.

Have in mind, a bug fix could also be "enabling integration with Azure cluster".

**Comment by bear454** [comment]
@jordimassaguerpla I'm fine with waiting a while to merge this in... there's no rush on it.

**Comment by vitoravelino** [comment]
I guess this is good to be merged since the release is out.

**Comment by vitoravelino** [comment]
Oh, there's no bsc number. =/

**Comment by bear454** [comment]
vitoravelino commented 5 days ago
> Oh, there's no bsc number. =/

This doesn't solve a "bug" - there is currently no known defect; just an effort to provide proper testing framework consistently across all environments; e.g. this is an _enhancement_ but is **not** user-facing.

**Comment by vitoravelino** [comment]
> This doesn't solve a "bug" - there is currently no known defect; just an effort to provide proper testing framework consistently across all environments; e.g. this is an enhancement but is not user-facing.

I know, you already have my +1. I guess using `enhancement#azure-spec` would solve the backport rule. Just guessing...

**Comment by bear454** [comment]
>  bear454 dismissed vitoravelino’s stale review

Well, _github_ dismissed the review when I changed the commit message... I didn't do _anything_ with reviews ;-)

**Comment by jordimassaguerpla** [comment]
@MaximilianMeister : It is ok to merge this one. Our package excludes files under spec directory and this can be useful when looking for regressions for new commits into 3.0 branch,

**Pull request merged**
