### PR TITLE
Ruby 2.5 was released last Xmas and is the latest stable ruby version

### PR DESCRIPTION
**Pull request by jordimassaguerpla**
let's enable it in travis to pass the tests

### CODE REVIEW

**Comment by flavio** [comment]
@jordimassaguerpla apparently it's failing, can you fix the issues withing this PR?

**Comment by bear454** [comment]
Can you bump `.ruby-version` as well, for `rbenv`? It's currently on a version that can't build on Tumbleweed.

**Comment by ereslibre** [comment]
@jordimassaguerpla What's the status of this? I see `.ruby-version` has conflicts now.

**Comment by Klaven** [comment]
@jordimassaguerpla and @ereslibre this seems forgotten about. i'm on a war path to clean up our old PR's that are sitting out here! Anything I can do to help with this? I see there are some failed tests. Let me know if I can help out!

**Comment by ereslibre** [comment]
What's the status of this, should we close this PR?

**Comment by jordimassaguerpla** [comment]
closing. This is old.

**Pull request closed without merging**
