### PR TITLE
Update dashboard layout

### PR DESCRIPTION
**Pull request by grahamhayes**

### CODE REVIEW

**Comment by grahamhayes** [comment]
@vitoravelino Is this commit OK to merge on its own?

**Comment by grahamhayes** [comment]
Tested by doing a fresh CaaSP install - UI shows correctly, and looks like: 
screenshot from 2017-06-09 13-43-43

**Comment by vitoravelino** [comment]
LGTM

**Comment by vitoravelino** [comment]
I guess this one is good to go. Waiting for reviews! :)

**Comment by grahamhayes** [comment]
I cannot approve this (as I opened the PR - but the commit is good, and tested, and not authored by me :) )

Count this as one of the 2 approvals.

**Comment by vitoravelino** [comment]
@grahamhayes I'm approving this counting as you since you can't do that because you were the one who opened the PR, ok?

**Pull request merged**
