### PR TITLE
Omit the default :each argument for RSpec hooks.

### PR DESCRIPTION
**Pull request by MalloZup**
http://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/HookArgument

### CODE REVIEW

**Comment by MalloZup** [comment]
i think the failure on the ci can be not considered, since i saw it on other prs

**Comment by ereslibre** [comment]
> i think the failure on the ci can be not considered, since i saw it on other prs

CI should be stable again, can you please rebase on top of master and push again?

**Comment by MalloZup** [comment]
Yop, i will do it no pb

**Comment by MalloZup** [comment]
@ereslibre  ok done :train:  afaik i saw that in your CI Jenkins Blue Ocean you need to accept manually to run the test, so just say ok when the moment comes. thx

**Comment by ereslibre** [comment]
Thank you @MalloZup! Waiting for CI results...

**Comment by MalloZup** [comment]
@ereslibre @vitoravelino thx for your feedback, even it was an easy fix. :call_me_hand:

**Pull request merged**
