### PR TITLE
Features/ui base

### PR DESCRIPTION
**Pull request by santiph**
Base implementation of latest design so far.
To see them in action, 6 new urls has been created for demo purposes:
`/ui-demo/1`
`/ui-demo/2`
`/ui-demo/3`
`/ui-demo/4`
`/ui-demo/5`
`/ui-demo/6`

[Annotations.pdf](https://github.com/kubic-project/velum/files/796624/Annotations.pdf)

### CODE REVIEW

**Comment by ereslibre** [comment]
There are some issues with the code coverage, syntax & testing, but we can fix that.

**Comment by jimmykarily** [comment]
:+1: I suggest we:

- squash all commits in one
- push the branch to kubic-project

We can then work on that branch to integrate it wit the backend

**Comment by ereslibre** [comment]
Maybe we could create `ui-integration` branch, and @santiph when creating PR's he would need to open them against `ui-integration` instead of `master`. We could squash them there, and work on them (it would depend on us at that point -- with our usual review process), keeping authority of the original commit, and being able to create another PR against `master` this time with everything working (100% coverage, no rubocop errors...)

**Comment by mssola** [comment]
@ereslibre in favor of the dedicated branch. That's how we did it with @cyntss in the past.

**Comment by MaximilianMeister** [comment]
as we merged the code with https://github.com/kubic-project/velum/issues/55 I think we can close this. thanks!

**Pull request closed without merging**
