### PR TITLE
made changes so project id and domain id can be used for openstack

### PR DESCRIPTION
**Pull request by tdaines42**
bsc#1091809

### CODE REVIEW

**Comment by tdaines42** [comment]
[Bug 1091809 - openstack CPI authentication with tenant-name and domain-name fails on engcloud.prv.suse.net](https://trello.com/c/zRnJUMrG/841-bug-1091809-openstack-cpi-authentication-with-tenant-name-and-domain-name-fails-on-engcloudprvsusenet)

**Comment by mjura** [comment]
How about also adding UserID?

**Comment by kiall** [comment]
> I agree with adding Domain ID as Project ID as alternative options to use, but we have to adopt UI to choose for using NAME's or ID's values by users.

Yea, the salt side does this already - if the IDs are specified, they are what is used. Once this is ready, I wanted to ask @vitoravelino to make further changes to disable the domain / project name fields if anything is entered into the ID fields (and vica versa)

> How about also adding UserID?

I believe there is no need. Usernames are required to be unique within a given domain.

**Comment by mjura** [comment]
> Yea, the salt side does this already - if the IDs are specified, they are what is used. Once this is ready, I wanted to ask @vitoravelino to make further changes to disable the domain / project name fields if anything is entered into the ID fields (and vica versa)

Ok, let's do this in separate PR

**Comment by vitoravelino** [comment]
> Yea, the salt side does this already - if the IDs are specified, they are what is used. Once this is ready, I wanted to ask @vitoravelino to make further changes to disable the domain / project name fields if anything is entered into the ID fields (and vica versa)

I can help with that after we merge this. :wink:

**Pull request merged**
