### PR TITLE
WIP: update mysql2 gem

### PR DESCRIPTION
**Pull request by MaximilianMeister**
it has updated to a new minor release in factory

factory#bump

Signed-off-by: Maximilian Meister <mmeister@suse.de>

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
before merging, we need to copy the new mysql gem to obs/ibs

**Comment by MaximilianMeister** [comment]
setting to WIP because of https://github.com/brianmario/mysql2/issues/950

seems that rails 4.2 has not yet caught up with the dependency change

**Comment by ereslibre** [comment]
What's the status of this PR? Should we close it?

**Comment by jordimassaguerpla** [comment]
we should fix the tests.

**Comment by MaximilianMeister** [comment]
velum is not in factory anymore, this is less of an issue now. i'd say we can keep it on hold until we have more time to test an update

**Comment by MalloZup** [comment]
This GitHub PR is unactive since 30. Is this GitHub PR still needed? Please close or update it accordingly.
         This reminder is autogenerated by https://github.com/MalloZup/blacktango

**Pull request closed without merging**
