### PR TITLE
BSC#1093565: Dynamically adjust cluster growth based on existing cluster size

### PR DESCRIPTION
**Pull request by bear454**
Resolves [Bug 1093565 - User is forced to add nodes to cluster](https://bugzilla.suse.com/show_bug.cgi?id=1093565) by detecting that the user has _already_ added nodes to the cluster, and allow them to add zero or more additional nodes to the cluster on subsequent visits.

### CODE REVIEW

**Comment by bear454** [comment]
First time through:
screenshot-first-view

Subsequent visit (after adding 3 nodes):
screenshot-second-view

**Comment by bear454** [comment]
[Bug 1093565 - User is forced to add nodes to cluster](https://trello.com/c/pMtpbw1y/996-bug-1093565-user-is-forced-to-add-nodes-to-cluster)

**Comment by jordimassaguerpla** [comment]
should this be backported to release-3.0 ?

**Comment by bear454** [comment]
jordimassaguerpla commented 12 minutes ago:
> should this be backported to release-3.0 ?

Now that it's been accepted, I will backport for both `release-3.0` and `release-2.1`, where the bug was reported.

**Comment by jordimassaguerpla** [comment]
@bear454 : Unless this has to be released before 3.0, you don't need to backport to 2.1.

**Comment by bear454** [comment]
@jordimassaguerpla It _absolutely_ needs to be backported to 2.1!

**Comment by jordimassaguerpla** [comment]
ok. Then go ahead :)

**Pull request merged**
