### PR TITLE
Correctly display the logo

### PR DESCRIPTION
**Pull request by MaximilianMeister**
SVG had wrong width, 300 instead of 314. For some reason
the text appeared cropped only in Firefox.

After saving the SVG with the correct width, logo now
is displayed properly.

bsc#1062832

Signed-off-by: Maximilian Meister <mmeister@suse.de>

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
the image gets compiled with `300px`, see https://github.com/kubic-project/velum/blob/master/app/assets/images/logo.svg?short_path=dccd7d4#L22

**Comment by vitoravelino** [comment]
I wasn't able to reproduce the error in my firefox v57. Logo now seems misaligned with the rest of the page (both chrome and firefox).

screenshot 2017-10-13 11 24 04

**Comment by vitoravelino** [comment]
@MaximilianMeister the name was larger than 300px, that's why it was appeared cropped in Firefox. I fixed the width and also converted from a font to a path object.

**Comment by MaximilianMeister** [comment]
@vitoravelino tested again, looks good. thanks for the change

**Comment by monstermunchkin** [comment]
[Bug 1062832 - Small cosmetic bug with title display on velum](https://trello.com/c/7I7RyK0s/411-bug-1062832-small-cosmetic-bug-with-title-display-on-velum)

**Pull request merged**
