### PR TITLE
Use --non-interactive flag for non interactive mode in dev env start script

### PR DESCRIPTION
**Pull request by jimmykarily**
We need the non interactive mode for the script to be used from other
scripts (e.g. in the e2e-tests project)

### CODE REVIEW

**Comment by ereslibre** [comment]
I would do the other way around. It's easier to add "--non-interactive" to our e2e-tests that to ask the user for a new flag. However, LGTM, I always clean up anyways :)

**Comment by jimmykarily** [comment]
getopts is [limited to single character flags](http://stackoverflow.com/questions/402377/using-getopts-in-bash-shell-script-to-get-long-and-short-command-line-options). I will use `-r` as in `*r*eplace containers`.

**Comment by jimmykarily** [comment]
Used `--non-interactive` after all

**Comment by mssola** [comment]
@jimmykarily @ereslibre yeah, it's what an opensuse guy would expect 😉

**Comment by ereslibre** [comment]
Anyone interested in this project would be the user. We are users too,
actually 🤗

**Pull request merged**
