### PR TITLE
[2.1] Backport public cloud support to 2.x

### PR DESCRIPTION
**Pull request by bear454**
Includes applicable commits/code from the following PRs:

* #403 Inject cloud framework
* #406 Consistent representation of public cloud instance types
* #438 Adapt velum to build a cluster in EC2
* #449 Azure integration
* #488 Public Cloud fixes

### CODE REVIEW

**Comment by bear454** [comment]
[[Public Cloud] https://github.com/kubic-project/velum/pull/467](https://trello.com/c/FGGrtAbl/741-public-cloud-https-githubcom-kubic-project-velum-pull-467)

**Comment by bear454** [comment]
I added the cherry-pick references, @MaximilianMeister . Please be aware there were adaptations along with the backport (e.g. back to the old external pillar implementation) .

**Comment by bear454** [comment]
Added backport commits from #488 .

**Comment by bear454** [comment]
Fixed a misnamed pillar in 8a186f5.

**Comment by kiall** [comment]
I've moved this PR from `release-2.0` to `release-2.1`. We're still getting that branch setup, so please ignore the CI fail for now - the Build Service hasn't built the images we need for CI yet..

**Comment by ereslibre** [comment]
@bear454 If you have tested this and it's working fine feel free to merge.

**Pull request merged**
