### PR TITLE
Fix kubelet arguments for version >= 1.6.1

### PR DESCRIPTION
**Pull request by ereslibre**

### CODE REVIEW

**Comment by PI-Victor** [comment]
ah, so that's what i was doing wrong. i was passing --kubeconfig instead. it didn't make sense to me to pass manifests to kubeconfig but i didn't give it a second look. testing now.

**Comment by mjura** [comment]
@ereslibre : Should we fix also kubernetes-kubelet package and /etc/kubernetes/kubelet file?

**Comment by ereslibre** [comment]
@mjura I don't think we need to change that, because by default it still is `/etc/kubernetes/manifests`, and I think the only place where we were overriding this manifest location is here in velum.

**Comment by PI-Victor** [comment]
tested and works. LGTM.

**Pull request merged**
