### PR TITLE
Clarification on the discovery page

### PR DESCRIPTION
**Pull request by mssola**
Signed-off-by: Miquel Sabaté Solà <msabate@suse.com>

### CODE REVIEW

**Comment by mssola** [comment]
It's not enough that nodes are up and running, but they also need to be accepted on the "Pending nodes"  table that is located below.

**Comment by vitoravelino** [comment]
@mssola I'm going to add some text when the pending nodes panel is empty too as you suggested [here](https://github.com/kubic-project/velum/pull/206#issuecomment-310637836) on https://github.com/kubic-project/velum/pull/213.

**Comment by flavio** [comment]
LGTM

**Comment by mssola** [comment]
My forced push was simply a rebase, so the old approvals also applied.

**Pull request merged**
