### PR TITLE
Public Cloud: Add support for bootstrapping in Google Compute

### PR DESCRIPTION
**Pull request by bear454**
(cherry picked from commit 446f412a3fd871bfae8429d9131fe462cbbb0d5e)

### CODE REVIEW

**Comment by bear454** [comment]
[Public Cloud: Add support for bootstrapping in Google Compute](https://trello.com/c/N0jyJj5v/1051-public-cloud-add-support-for-bootstrapping-in-google-compute)

**Comment by flavio** [comment]
Overall LGTM, requesting a review from other velum developers.

**Comment by bear454** [comment]
I can rebase it, if that's what's expected... if you all agree to put your reviews back in after :)

**Comment by bear454** [comment]
Rebasing made no change...

**Comment by bear454** [comment]
For reference, this _is_ released code:

https://build.suse.de/package/view_file/SUSE:SLE-12-SP3:Update:Products:CASP21:PublicCloud/velum/0002-Add-support-for-bootstrapping-in-Google-Compute.patch?expand=1

**Comment by ereslibre** [comment]
What's the status of this PR?

**Pull request closed without merging**
