### PR TITLE
make 503 page more generic

### PR DESCRIPTION
**Pull request by MaximilianMeister**
bsc#1080636

Signed-off-by: Maximilian Meister <mmeister@suse.de>

### CODE REVIEW

**Comment by jordimassaguerpla** [comment]
Could this be backported to release-3.0 branch? Even if it has to be released as a maintenance update.

**Comment by MaximilianMeister** [comment]
> Could this be backported to release-3.0 branch? Even if it has to be released as a maintenance update.

@jordimassaguerpla underlying bug is a P2, and showing a branded page instead of just a 503 Service Unavailable text I think is more of a cosmetic issue. we'd need to backport a few commits from velum/salt/manifests and the branding package itself. do you think it's worth it?

**Comment by jordimassaguerpla** [comment]
Can  we fix the bug for 3.0 without the branding package? I would rather prefer not to add new packages in 3.0

**Comment by MaximilianMeister** [comment]
> Can we fix the bug for 3.0 without the branding package? I would rather prefer not to add new packages in 3.0

@jordimassaguerpla i think there's no clean way, as we need to have the files installed on the admin host. we could install the static pages via another existing package but i dont know which one would fit.

**Pull request merged**
