### PR TITLE
bsc#1098085 Add nodes in public clouds

### PR DESCRIPTION
**Pull request by bear454**
* Requires #595
* Requires #610

Adapt public cloud bootstrap views & controller actions to enable adding nodes after boostrap.

### CODE REVIEW

**Comment by bear454** [comment]
@MaximilianMeister - a review would be appreciated.

**Comment by bear454** [comment]
[Bug 1098085 - No UI for accessing node bootstrap info after setup](https://trello.com/c/JBsPkG6f/1086-bug-1098085-no-ui-for-accessing-node-bootstrap-info-after-setup)

**Comment by bear454** [comment]
Backport for `release-3.0` will require #596 and #622 to be merged.

**Comment by MaximilianMeister** [comment]
> Requires #595
> Requires #610

both are already merged

**Comment by bear454** [comment]
MaximilianMeister commented 7 hours ago ...

> both are already merged

Yes; in this case I can't even make the pull requests until the required PRs are merged ;-)

Now I wait for #596 and #622...

**Pull request merged**
