### PR TITLE
Feature: external certs

### PR DESCRIPTION
**Pull request by nanoscopic**

### CODE REVIEW

**Comment by MalloZup** [comment]
This GitHub PR is unactive since 30. Is this GitHub PR still needed? Please close or update it accordingly.
         This reminder is autogenerated by https://github.com/MalloZup/blacktango

**Comment by jordimassaguerpla** [comment]
@dannysauer Hi! CI should be fixed now. Please keep an eye on the test results. If this is green, please proceed to get the needed approvals and merge.

Then, could you please backport ALL the needed PR for external certificates to the *private* release-3.0 branch, get the approvals there and watch the CI becoming green.
thanks

**Comment by dannysauer** [comment]
Awesome, thanks. I'll check this stuff out next week when I'm back "in the office."

**Comment by MalloZup** [comment]
green again

**Review by dannysauer — APPROVED** [review]
This appears to work properly with the salt backend; approving.

**Comment by jordimassaguerpla** [comment]
I see everything green... can you merge and backport?

**Pull request merged**
